---
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: install apache tomcat package
      yum: pkg=tomcat state=latest
    
    - name: cloning file from git
      command: src=C:\Program Files (x86)\Jenkins\workspace dest=/usr/share/tomcat/webapps
